syntax = "proto3";

package com.coralogix.ingress.otlp.v1;

option java_multiple_files = true;
option java_package = "com.coralogix.ingress.otlp.v1";
option java_outer_classname = "TelemetryProto";

import "opentelemetry/proto/logs/v1/logs.proto";
import "opentelemetry/proto/trace/v1/trace.proto";
import "opentelemetry/proto/metrics/v1/metrics.proto";

message Telemetry {
  repeated opentelemetry.proto.logs.v1.ResourceLogs logs = 1;
  repeated opentelemetry.proto.trace.v1.ResourceSpans spans = 2;
  repeated opentelemetry.proto.metrics.v1.ResourceMetrics metrics = 3;
  repeated string epsagon_traces = 4;
}